#!/bin/bash
systemctl daemon-reload
chown daemon:daemon /usr/local/share/SYS_MONITOR/config.txt
if systemctl is-enabled sys_monitor.service > /dev/null; then
    systemctl restart sys_monitor.service
fi
